### ISSUE TITLE
Generate `src/index.ts` and `test/index.test.ts` for typescript/jsii projects

### ISSUE THREAD

**Issue by eladb** [eladb/projen#11]

**Comment by andrestone** [comment]
Just touching those or is there any template code we could add?

**Comment by eladb** [comment]
I would put some rudimentary code like:

`src/index.ts`

```
export * from ‘./hello.ts’;
```

`src/hello.ts`

```ts
export class Hello {
  public world() {
    return “Hello, world!”;
  }
}
```

`test/hello.test.ts`

```ts
import { Hello } from ‘../src’;

test(‘hello’, () => {
  expect(new Hello().world()).toBe(‘Hello, world!’):
}
```

The idea is that after `projen init X` you’d be able to run `yarn build` and it will be successful.

**Comment by eladb** [comment]
Done.
