### ISSUE TITLE
The `types` path in `package.json` is missing a `/`

### ISSUE THREAD

**Issue by bartcallant** [eladb/projen#132]
After seeing a talk from @eladb during the CDK Day I created a test project to see `projen` in action. And during some exploring I noticed the `types` path in the `package.json` file is missing a `/` between the lib dir and the entrypoint file name when using the `TypeScriptProject` template.

## Steps to reproduce
Initialize a project with the following `.projenrc.js`: 
```
const { TypeScriptProject } = require("projen");

const project = new TypeScriptProject({
  name: "test-project"
});

project.synth();
```

## Version
`projen`: 0.3.77

## Possible solution
I think adding the `/`  between `${path.dirname(this.entrypoint)}` and `${path.basename(this.entrypoint, '.js')}` seems like it enough to make this work. 
By modifying the compiled output, I tested this fix and it seems to work as expected. There do not seem to be any tests yet for the `TypeScriptPoject`, so not really sure how to continue there. I can already create a PR for the changes: https://github.com/bartcallant/projen/commit/39e9da0aeff7269809190d3b136bef6fd653ecd1

**Comment by eladb** [comment]
PR is welcome
