### ISSUE TITLE
Start menu entries not removed in AWS CDK app

### ISSUE THREAD

**Issue by hoegertn** [eladb/projen#145]
The AWS CDK app removes some scripts from `package.json` but these scripts still show up un the generated start menu configuration.

**Comment by eladb** [comment]
Yakk. I am wondering if we should somehow bind the start menu entires to the scripts so that when a script is removed, the menu entry is removed with it

**Comment by hoegertn** [comment]
That is what I was thinking. Maybe during synth you could check the list of start entries and remove all without existing scripts.

**Comment by eladb** [comment]
I would try to establish a "stronger" connection between the start entry and the script so that when a script is deleted, it's easy to trace to the start menu entry and delete it

**Comment by eladb** [comment]
Resolved by #228
