### ISSUE TITLE
feature request : customizable projen upgrade schedule

### ISSUE THREAD

**Issue by pahud** [eladb/projen#153]
At this moment, projen upgrades itself  and opens PRs on a daily basis, which is a little bit annoying if the downstream repos are not going to stick to the latest projen version.

Would be great to have a customizable schedule expression.

https://github.com/eladb/projen/blob/9cea082317765219efc43c9f09e3356024c833d9/src/projen-upgrade.ts#L45

**Comment by eladb** [comment]
Contributions are welcome

**Comment by pahud** [comment]
> Contributions are welcome

Sure. Let me do it.
