### ISSUE TITLE
Inquiry: Creating Additional Files in Repo

### ISSUE THREAD

**Issue by JordanSinko** [eladb/projen#159]
This is just a question I have after searching the docs.

Is there a common way to create additional files within the project, similar to JsonFile? Is this something that should be manually created when needed? 

An example of this would be a `buildspec.yml` for CodeBuild. Personally, I've created a class that does this for me but I was just curious if this was a native feature.

```
class ContentFile extends FileBase {
  constructor(project, path, options) {
    super(project, path, options);
    this.options = options;
  }

  synthesizeContent() {
    return this.options.content;
  }
}

new ContentFile(project, ".prettierignore", {
  content: `package.json
API.md
`,
});
```

**Comment by mbonig** [comment]
Could this be done by creating a new class that inherits form Construct and then overriding the synthesize method to create the files?

**Comment by JordanSinko** [comment]
Ultimately it's what I did with the class above. I guess I wanted to get an idea about direction of creating said files, via generation with Projen or manually creating said files. I think I prefer the former.

**Comment by mbonig** [comment]
I wouldn't put any file creation by hand.. always have it wrapped in constructs. That's what the API expects and things will generally work best when you follow that convention.

**Comment by eladb** [comment]
If you want to create a JSON file, you can use:

```js
new JsonFile(project, '.markdownlint.json', {
  obj: {
    "default": true,
    "commands-show-output": false,
    "line-length": {
      "line_length": 200
    }  
  }
});
```

Contributions are welcome for YAML support.
