### ISSUE TITLE
Templates vs Project Classes

### ISSUE THREAD

**Issue by andrestone** [eladb/projen#18]
Hey there!

With the latest commits, we now have 1:1 relation between classes and initialization options. But, in fact, one class could have many templates to serve many different purposes. 

So, the question is: should we have a templating system or just go creating project classes to support common use cases? None of those and stick with current state (single template per project type) ?

**Comment by eladb** [comment]
_projen_ is all about avoiding templates. "Templates are evil" is our moto.

The main principle is that project **types** offer a surface area for users to define their project and we can easily implement a hierarchy of project types if there are use cases for more specific configuration.

For example, `JsiiProject` is derived from `TypeScriptProject` and specializes it for jsii use cases.

Let's take a use case you have in mind and I'll show you how we can add a project type for it.

# #templatesareevil

**Comment by andrestone** [comment]
I'm not necessarily advocating for templates, I just wanted to clarify what is the better path for extending projen to support more specific use cases, as I thought we were working towards allowing templates since [this](https://github.com/eladb/projen/issues/10#issue-652654375).

There's a multitude of _project_ "types" that support various use cases and I think it's important to make clear to which degree these use cases would be supported out-of-the-box. IMO, the downside of using "types" instead of templates is that the codebase might get pretty bloated and hard to maintain (if we're willing to support many), while templates live outside of the core APIs and therefore introduce less friction. I also see it as an easier path to adoption, since more flexibly supporting different use cases is welcoming (**if I have a cdk-jsii-construct template (or type), there's very little to customize in comparison to starting with the jsii type**).

For example, here is what's currently working on my fork (API defo needs a better interface, but you get the idea):

#### Adding new project from template and customizing
`.projenrc.js`
```typescript
const webFrontEnd = NodeProject.fromTemplate({
  templateName: 'typescript',
  copyFiles: true,
  modifier: (proj) => {
    proj.addFields({
      name: 'my-project'
    });
    proj.addFields({
      keywords: ['hello', 'from', 'async']
    });
  }
});
webFrontEnd.then(proj => proj.synth());
```

In the example above I'm using a template (which consists of a .projenrc.js file and sample code files) to instantiate a new _projen_ project with changes. Since I'm using actual templates, changing template files is more flexible and straight forward.

I'm also using templates to manage monorepo packages like this:

#### Creating a monorepo project and adding a custom package based on template:

`.projenrc.js`
```typescript
const myMonorepoProject = new LernaProject({
  name: 'root',
  lernaVersioning: true,
  ...common,
});

myMonorepoProject.addPackageFromTemplate({
  template: 'typescript',
  modifier: (proj) => {
    proj.addFields({
      name: 'dynageo'
    });
    proj.addFields({
      keywords: ['hello', 'from', 'async']
    });
  }
});
myMonorepoProject.synth();
```


## Using classes instead of templates just make the above easier to implement. But how many types are we willing to support? Maybe open for extensibility with a _projen+_ kind of package?

**Comment by eladb** [comment]
I'd like to start by using project types as the main vehicle for offering abstraction and not templates. Yes, they require thinking about APIs and surface area, but that's that whole point. Templates are evil exactly for that reason - they "seem easy" at first but very quickly they become completely unmaintainable and impossible to update.

When we reach 300 project types, we'll see how we can decentralize the ecosystem (it is always possible to import a project type from a library). At the moment, I think there is some value in keeping things simple and centralized. I added an Ecosystem section to readme with some info.

**Comment by andrestone** [comment]
Awesome!
