### ISSUE TITLE
Add .idea to .npmignore for webstorm developers

### ISSUE THREAD

**Issue by abelmokadem** [eladb/projen#222]
Currently the `.npmignore` file in `TypeScript` contains `.vscode`. That works for vscode users but not for webstorm users.

**Comment by abelmokadem** [comment]
Current workaround:

```
const project = new TypeScriptProject({
    npmignore: [
        "/.idea"
    ],
```

**Comment by eladb** [comment]
Sounds good. Contributions are welcome
