### ISSUE TITLE
"Anti-tamper check after build"

### ISSUE THREAD

**Issue by jialechan** [eladb/projen#35]
Use version 0.3.13 but still can't pass this check 😢

https://github.com/jialechan/cdk-elasticache-monitor/runs/922973170?check_suite_focus=true

**Comment by eladb** [comment]
Your [build log](https://github.com/jialechan/cdk-elasticache-monitor/runs/922973170?check_suite_focus=true#step:10:15) suggests that you forgot to add some peer dependencies. What happened is that jsii updated your pakcage.json file for you and that "tampered" with the synthesized projen output.

The solution is to add the following as peer dependencies in your `projenrc.js` file:

```json
"constructs": "3.0.4",
"@aws-cdk/core": "1.55.0",
"@aws-cdk/aws-lambda": "1.55.0",
"@aws-cdk/aws-cloudwatch": "1.55.0",
"@aws-cdk/aws-sns": "1.55.0",
"@aws-cdk/aws-sns-subscriptions": "1.55.0",
"@aws-cdk/aws-cloudwatch-actions": "1.55.0"
```

**Comment by jialechan** [comment]
Great! Thanks a lot!

**Comment by jialechan** [comment]
> Your [build log](https://github.com/jialechan/cdk-elasticache-monitor/runs/922973170?check_suite_focus=true#step:10:15) suggests that you forgot to add some peer dependencies. What happened is that jsii updated your pakcage.json file for you and that "tampered" with the synthesized projen output.
> 
> The solution is to add the following as peer dependencies in your `projenrc.js` file:
> 
> ```json
> "constructs": "3.0.4",
> "@aws-cdk/core": "1.55.0",
> "@aws-cdk/aws-lambda": "1.55.0",
> "@aws-cdk/aws-cloudwatch": "1.55.0",
> "@aws-cdk/aws-sns": "1.55.0",
> "@aws-cdk/aws-sns-subscriptions": "1.55.0",
> "@aws-cdk/aws-cloudwatch-actions": "1.55.0"
> ```

Great! Thanks a lot!
