### ISSUE TITLE
Why Semver.pinned() in addPeerDependencies()?

### ISSUE THREAD

**Issue by jialechan** [eladb/projen#41]
Hello Eladb:

I would like to asking you why 'addPeerDependencies()' use 'Semver.pinned()' but not just like 'addDevDependencies()' use 'v.spec' when pinnedDevDependency eq ture? Is there something diff between devDependencies and peerDependencies? 

Thanks a lot!

https://github.com/eladb/projen/blob/a715a069e1d6f0ed4608a93f04ae086f567ed94b/src/node-project.ts#L602-L617

**Comment by eladb** [comment]
The rationale is that if you declare a peer dependency on version `^1.0.0` but then actually test against `1.78.0` then your consumers may break if they use a lower version. 

If you declare that you require at least `1.0.0` you want to test against the lowest version
