### ISSUE TITLE
Using 3rd Party Projects

### ISSUE THREAD

**Issue by skorfmann** [eladb/projen#46]
I'm wondering what the best way is for using a project generator class which is not part of this project. There might be project generators which only make sense to a small or private audience. Is that even a case which will be supported?

**Comment by skorfmann** [comment]
The best idea I had so far: Make the 3rd party package executable as well, and invoke `projen` internally.

**Comment by eladb** [comment]
It should be trivial to declare generator classes that are inside the project source tree itself but we also need a story to take an npm dependency on a module that has classes in it.

**Comment by skorfmann** [comment]
> we also need a story to take an npm dependency on a module that has classes in it.

Yes, that's what I meant.

**Comment by eladb** [comment]
Technically, if you install an npm module which exports projen classes through `devDependencies` projen should be able to find it. The only problem is how to bootstrap this if you still don't have a `package.json`. 

projen uses a [magic trick] to allow that bootstrapping but it only works for projen itself right now. Maybe we can do something similar?

[magic trick]: https://github.com/eladb/projen/blob/6d38ba8dd8eee899b517b16ccb30600a9722eed0/src/cli.ts#L31

**Comment by eladb** [comment]
Resolved by #212
