### ISSUE TITLE
projen:upgrade fails

### ISSUE THREAD

**Issue by skorfmann** [eladb/projen#56]
A local `yarn projen:upgrade` looks like this:

![Screenshot 2020-08-11 at 10 32 54](https://user-images.githubusercontent.com/136789/89875883-1a50e600-dbbe-11ea-8224-879718f71157.png)

Which fails in [CI](https://github.com/skorfmann/cdktf-provider-project/runs/969930520?check_suite_focus=true) with this error:

![Screenshot 2020-08-11 at 10 34 23](https://user-images.githubusercontent.com/136789/89875975-440a0d00-dbbe-11ea-8a82-06675108bcf7.png)

That's using `TypeScriptProject`

**Comment by eladb** [comment]
Yes. That's pretty annoying. I've been seeing those too. 

Any ideas?

**Comment by skorfmann** [comment]
> Any ideas?

- Just run `npx projen@latest` would be the easiest, but has drawbacks for major version changes of course
- Reading the currently locked version from the lockfile (e.g. `yarn list | grep projen`)
- Use another token (e.g. https://github.com/tibdex/github-app-token) - but that Github App would be quite an overhead 

Other ideas?
