### ISSUE TITLE
scheduled ProjenUpgrade failed

### ISSUE THREAD

**Issue by pahud** [eladb/projen#66]
Hi @eladb 

Looks like the scheduled `ProjenUpgrade` will need to update the `yarn.lock` but `--frozen-lockfile` was passed.

https://github.com/pahud/cdk-spot-one/runs/987656093?check_suite_focus=true

Any comments on this ?

**Comment by eladb** [comment]
It doesn't seem like this is a result of the update but rather a result of the repo bootstrapping. 

Try to run projen locally and commit the updated lockfile and let me know if this persists.
