### ISSUE TITLE
Semver should accept less strict version constraints

### ISSUE THREAD

**Issue by skorfmann** [eladb/projen#75]
When attempting to declare a dependency like this `Semver.caret('0.0')` an invalid Semver error is thrown. According to [this ](https://stackoverflow.com/a/33067594) it should be possible. 

Out of curiosity, what was the motivation to roll your own semver implementation rather than using something like https://www.npmjs.com/package/semver ?

**Comment by eladb** [comment]
Stupid decision basically. The dependencies api is basically deprecated (unofficially yet) in favor of a new `deps` API in which you just specify the module name and projen records the version from package.json. 

So you can basically use tools like dependabot and `ncu`.

And if you want you can specify server inside the module name `foo@^2`.

Would be happy if you want to take it for a spin and let me know if that works.

**Comment by eladb** [comment]
Replaced by `deps`, `devDeps` etc. `Semver` is about to be deprecated thank god.
