### ISSUE TITLE
Anti-tamper check failed with the 'start' script

### ISSUE THREAD

**Issue by pahud** [eladb/projen#85]
I am having the `Anti-tamper check` when I commit the `package.json` and `.projenrc.js` together to my aws cdk construct lib repo:

<img width="1623" alt="圖片" src="https://user-images.githubusercontent.com/278432/91519219-92d8d600-e924-11ea-8dd5-e35fa5e2b5bd.png">

https://github.com/aws-samples/cdk-serverless-lamp/runs/1039788734?check_suite_focus=true

Affected version: projen@0.3.48

It was working in `0.3.47`.

Hi @eladb 

Any comments? Did I miss anything?

**Comment by pgarbe** [comment]
Same here

**Comment by pgarbe** [comment]
It's also strange that if I run `npx projen@0.3.47` it doesn't change anything. I expected that the generated files will be changed and using v0.3.47 (for example in .github/workflows/build.yml)

**Comment by pahud** [comment]
> It's also strange that if I run `npx projen@0.3.47` it doesn't change anything. I expected that the generated files will be changed and using v0.3.47 (for example in .github/workflows/build.yml)

try

```sh
rm -rf node_modules
npx projen@0.3.47 && yarn install 
```

And if the workflow files are not updated, delete them and run the commands above again :-)

**Comment by pgarbe** [comment]
That didn't work for me, as it still installs 0.3.48. But, the `ConstructLibraryAws` project allows to define a `projenVersion` which I set to 0.3.47. 

Actually, there's also a `antitamper` property which can be set to false. Which doesn't solve the problem, but might be another workaround.

**Comment by pgarbe** [comment]
@pahud You were right. Deleting the node_modules folder helped. the `projenVersion` property somehow doesn't change anything.

**Comment by pahud** [comment]
> @pahud You were right. Deleting the node_modules folder helped. the `projenVersion` property somehow doesn't change anything.

I am pinning it to 0.3.47 like this

https://github.com/aws-samples/cdk-serverless-lamp/blob/master/.projenrc.js

And this

https://github.com/aws-samples/cdk-serverless-lamp/blob/db32c856d997271fb74ee475af29aa54a9e4f562/.projenrc.js#L48-L50
