### ISSUE TITLE
Permission denied on package.json

### ISSUE THREAD

**Issue by pgarbe** [eladb/projen#90]
I'm adding projen to my CDK construct library using the `ConstructLibraryAws` project. As my construct includes a NodeJsFunction, it fails during tests as it can't access the package.json file. If I change the permissions it works until they are resetted by `npx projen`.

>    EACCES: permission denied, open '.../package.json'

**Comment by pgarbe** [comment]
Solved it. The root cause was that I forgot the /src subfolder to be part of the entry file of the NodejsFunction. Because of that the parcel bundler thought it's in root and started to create it's temproary package.json file. That failed because the existing one was readonly. Now, the temporary package.json is created in /src folder where also the lambda code is located.

**Comment by pgarbe** [comment]
I solved it by moving my lambda code in a subfolder and adding a separate package.json. The problem is that NodejsFunction looks up the path for the next available package.json and modifies it for the bundling process. That's not possible with the package.json from root folder as it's write protected. 

That means using a lambda function as described [here](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-nodejs-readme.html#nodejs-function) is not possible.

**Comment by jogold** [comment]
@eladb yes, this is https://github.com/aws/aws-cdk/issues/9673#issuecomment-673999457

Would it be possible to provide an option so that `projen` doesn't make the `package.json` read-only?

**Comment by eladb** [comment]
I am changing `package.json` to be read/write as part of https://github.com/eladb/projen/pull/91
